#!/bin/bash
plistCmd="/usr/libexec/PlistBuddy -c"
configFile="${WEBDEV_PATH}/etc/webdev-config.plist"
function getConfig {
	returnValue=`${plistCmd} "print ${1}" ${configFile} 2>/dev/null` 
	if [ $? == 0 ] ; then
		echo "$returnValue"
		return 0
	else
		return 1
	fi
}

function setConfig {
	${plistCmd} "Set ${1} ${2}" ${configFile} # 2>/dev/null
	return $?
}