#!/bin/bash
_bashcompletion_paths="${_bashcompletion_paths} install_mongo"

function install_mongo_deps {
	return "brew"
}

function install_mongo_check {
	brew list mongo > /dev/null 2>&1
	return $?
}

function install_mongo_opts {
	echo "webdev_install_mongo_opts=\"`brew options mongo | grep -vE "^\s+" | grep -vE "^$" | tr "\\n" ' '`\""
}

function install_mongo_case {
	case ${1} in		
		install)
			install_mongo_check
			if [ $? == 0 ] ; then
				printKO "Service mongo" "ALREADY_INSTALLED"
				return 1
			else
				brew install mongo "${@:2}" > /dev/null 2>&1
				ret=$?
				if [ $? == 0 ] ; then
					printOK "Service mongo" "INSTALLED"
				else
					printKO "Service mongo" "FAILED"
				fi
				return ${ret}
			fi
		;;
	esac
}