#!/bin/bash
#servicesInstallable=`ls -1 ${WEBDEV_PATH}/share/bash-include/install/service | grep -v "^service"|tr "\\n" ' '`
_bashcompletion_paths="${_bashcompletion_paths} install_mysql"

function install_mysql_opts {
	echo "webdev_install_mysql_opts=\"`brew options mysql | grep -vE "^\s+" | grep -vE "^$" | tr "\\n" ' '`\""
}

function install_mysql_case {
	case ${1} in		
		install)
			brew list mysql > /dev/null 2>&1
			if [ $? == 0 ] ; then
				printKO "Service mysql" "ALREADY_INSTALLED"
				return 1
			else
				brew install mysql "${@:2}" > /dev/null 2>&1
				ret=$?
				if [ $? == 0 ] ; then
					printOK "Service mysql" "INSTALLED"
				else
					printKO "Service mysql" "FAILED"
				fi
				return ${ret}
			fi
		;;
	esac
}