#!/bin/bash
#servicesInstallable=`ls -1 ${WEBDEV_PATH}/share/bash-include/install/service | grep -vE "^service"|tr "\\n" ' '`
phpversions=`ls -1 ${WEBDEV_PATH}/share/bash-include/install/php | grep -vE '^(php|extension)$'| tr "\\n" ' '`

_bashcompletion_paths="${_bashcompletion_paths} install_php"

for version in ${phpversions}
do
	require "install.php.${version}"
done


function install_php_opts {
	echo "webdev_install_php_opts=\"${phpversions}\""
}

function install_php_case {
	if [ "x${3}" == "x" ] ; then
		echo "Wrong argument"
		showHelp
	else
		if [[ ${phpversions} =~ ${3} ]] ; then
			install_php_${3}_case install "${@:4}"
		else
			echo "Wrong argument"
			showHelp
		fi
	fi 
}