#!/bin/bash
_bashcompletion_paths="${_bashcompletion_paths} install_php_php52"

function install_php52_deps {
	return "brew"
}

function install_php52_check {
	brew list php52 > /dev/null 2>&1
	return $?
}

function install_php_php52_opts {
	echo "webdev_install_php_php52_opts=\"`brew options ${WEBDEV_BREW_PHP_PREFIX}php52 | grep -vE "^\s+" | grep -vE "^$" | tr "\\n" ' '`\""
}

function install_php_php52_case {
	case ${1} in		
		install)
			install_php52_check
			if [ $? == 0 ] ; then
				printKO "Service php52" "ALREADY_INSTALLED"
				return 1
			else
				brew install php52 "${@:1}" --with-fpm  > /dev/null 2>&1
				ret=$?
				if [ $? == 0 ] ; then
					printOK "Service php52" "INSTALLED"
				else
					printKO "Service php52" "FAILED"
				fi
				return ${ret}
			fi
		;;
	esac
}